<?php
	//-------此為連接dadu_message資料庫的設定檔--------
	define("DB_TYPE","mysql");
	define("DB_HOSTNAME","localhost");
	define("DB_NAME","dadu_message");
	define("DB_USERNAME","root");
	define("DB_PASSWORD","");
	define("DB_CHARSET","utf8");
?>